### ISSUE TITLE
Regarding Speed Accuracy

### ISSUE THREAD

**Issue by GaneshKoushik313** [lucabrevi/Speed_tracking#2]
Hello Sir,
How can i increase accuracy in speed , can u help me in solving this issue

**Comment by jasonray716** [comment]
you should adjust camera calibration according to the position of camera related to the road.

**Comment by GaneshKoushik313** [comment]
And I have mounted camera in 20ft height, where can I set calibration value
for in code, I have changed blob lockon distance px value, is it correct??

**Comment by jasonray716** [comment]
you should change the parameters in this code snippet.

take a look [this](https://github.com/trevordonnelly/Speed_tracking/blob/master/mog_speed_tracking.py#L142)

**Comment by GaneshKoushik313** [comment]
Sir how can I change value for detecting only vehicles, because it's
detecting all the objects

**Comment by jasonray716** [comment]
well, in order to detect only vehicles, I recommend using Yolo deep neural network instead of my code.

Here is the result of my updated version. [Here](https://www.dropbox.com/s/r2mtvl09b161div/traffic_detection-2018-02-08_15.53.04.mp4?dl=0)

**Comment by GaneshKoushik313** [comment]
I used YOLO sir, but my main intension is to estimate speed of all moving
vehicles,but YOLO is only for detection purpose I think,

**Comment by jasonray716** [comment]
Please check above link that I attached.

**Comment by GaneshKoushik313** [comment]
Ok sir, i saw the result attached in the link,i am impressed with the way vehicle detecting and estimating speed of the vehicle using YOLO, can u give me some ideas regarding this?

**Comment by winnie1009** [comment]
> well, in order to detect only vehicles, I recommend using Yolo deep neural network instead of my code.
> 
> Here is the result of my updated version. [Here](https://www.dropbox.com/s/r2mtvl09b161div/traffic_detection-2018-02-08_15.53.04.mp4?dl=0)

Excuse me, if this project can be open source?
